services:
  laravel:
    container_name: 'rc_laravel'
    working_dir: '/app'
    build:
      dockerfile: './laravel.Dockerfile'
    ports:
      - '20000:20000'
    volumes:
      - '../rc.laravel:/app'
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=20000"
